spring.datasource.url=jdbc:sqlite:stream_cache.db
spring.datasource.driver-class-name=org.xerial.SQLiteJDBCDriver
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Automatically updates the database schema matching your Java entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true