package mapper;

import model.StorageFile;
import model.VideoMetadata;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class VideoMetadataMapperTest {

    private final VideoMetadataMapper mapper = new VideoMetadataMapper();

    @Test
    void toEntityMapsAllFieldsFromStorageFile() {
        StorageFile file = new StorageFile("id1", "movie.mp4", 1500L, "video/mp4", "https://thumb.example/1");

        VideoMetadata result = mapper.toEntity(file);

        assertThat(result.getFileId()).isEqualTo("id1");
        assertThat(result.getTitle()).isEqualTo("movie.mp4");
        assertThat(result.getFileSize()).isEqualTo(1500L);
        assertThat(result.getMimeType()).isEqualTo("video/mp4");
        assertThat(result.getThumbnailLink()).isEqualTo("https://thumb.example/1");
    }

    @Test
    void toEntityHandlesNullThumbnailLink() {
        // Drive files sometimes lack a thumbnailLink (e.g. not yet generated by Google);
        // confirms the mapper doesn't throw and just passes null through.
        StorageFile file = new StorageFile("id2", "clip.mp4", 500L, "video/mp4", null);

        VideoMetadata result = mapper.toEntity(file);

        assertThat(result.getThumbnailLink()).isNull();
    }
}
